extends: default

rules:
  line-length:
    max: 180
    level: warning
  indentation:
    spaces: 4
    indent-sequences: true
  truthy: disable          # Sigma uses unquoted yes/no-ish values in places
  comments:
    min-spaces-from-content: 1
  document-start: disable
